### ISSUE TITLE
Comparison: Classify rasters before extracting values vs classifying median of extracted values

### ISSUE THREAD

**Issue by echelleburns** [emlab-ucsb/offshoredatr#28]
We wanted to know how different results would be if we changed our classification order when our planning grid is an sf object. We currently first classify values, then use `exactextractr` to extract the classification values within the planning grid. What if we first extract the median raw value within the planning grid, then classify? 

I have run the following example using the square planning grid and bathymetry data: 

```
devtools::load_all()

area <- get_area(area_name = "Bermuda")
projection <- 'PROJCS["ProjWiz_Custom_Lambert_Azimuthal", GEOGCS["GCS_WGS_1984", DATUM["D_WGS_1984", SPHEROID["WGS_1984",6378137.0,298.257223563]], PRIMEM["Greenwich",0.0], UNIT["Degree",0.0174532925199433]], PROJECTION["Lambert_Azimuthal_Equal_Area"], PARAMETER["False_Easting",0.0], PARAMETER["False_Northing",0.0], PARAMETER["Central_Meridian",-64.5], PARAMETER["Latitude_Of_Origin",32], UNIT["Meter",1.0]]'
planning_square <- get_planning_grid(area, projection = projection, option = "sf_square")

# Option 1: What we're currently doing - using exactextract on classified data. 
bathymetry <- get_bathymetry(area_polygon = area)
depth_zones_square <- classify_depths(bathymetry, planning_grid = planning_square)

plot(depth_zones_square, border = FALSE)
```
![image](https://github.com/emlab-ucsb/offshoredatr/assets/40546424/edced7fc-75c6-4676-b66c-c1f1a22bd425)

```
# Option 2: Use exactextract to get the medians of values and then classify the medians
depth_zone_names <- c("epipelagic", "mesopelagic", "bathypelagic", "abyssopelagic", "hadopelagic")

projected_raster <- bathymetry %>% terra::project(terra::crs(planning_square))

classification_vec <- exactextractr::exact_extract(projected_raster, planning_square, 
                                                     function(value, cov_frac) 
                                                       ifelse(length(value) > 0, 
                                                              median(value, na.rm = T), 
                                                              NA))

classification_cut <- cut(classification_vec, 
                          breaks = (c(Inf, -200, -1000, -4000, -6000, -12000)), 
                          labels = rev(c(1,2,3,4,5)),
                          right = TRUE) %>%
  as.character() %>% 
  as.numeric()

stack_out <- 
  planning_square %>% 
  cbind(data.frame("classification" = classification_cut)) %>% 
  dplyr::mutate(value = 1, 
                classification_cut = classification, 
                classification = depth_zone_names[classification_cut]) %>% 
  tidyr::pivot_wider(names_from = "classification", values_from = "value", values_fn = ~mean(.x, na.rm = T)) %>% 
  dplyr::rename(geometry = x) %>% 
  dplyr::select(depth_zone_names[sort(unique(classification_cut))], geometry)

plot(stack_out, border = FALSE)
```
![image](https://github.com/emlab-ucsb/offshoredatr/assets/40546424/65cb09b6-73a2-4b7e-aae6-56835703e4a6)

```
# Check equals
knitr::kable(tibble::tibble(`Depth Zone` = depth_zone_names[depth_zone_names %in% colnames(depth_zones_square)], 
           `N cells (classify first, take value with highest overlap)` = as.numeric(colSums(depth_zones_square %>% sf::st_drop_geometry(), na.rm = T)), 
           `N cells (classify last, from medians)` = as.numeric(colSums(stack_out %>% sf::st_drop_geometry(), na.rm = T))))
```
|Depth Zone    | N cells (classify first, take value with highest overlap)| N cells (classify last, from medians)|
|:-------------|---------------------------------------------------------:|-------------------------------------:|
|epipelagic    |                                                        39|                                    42|
|mesopelagic   |                                                        18|                                    27|
|bathypelagic  |                                                       339|                                   362|
|abyssopelagic |                                                     18483|                                 18448|

It looks like classifying last, from the median raw values introduces a more cells in the shallower depth groups, and fewer cells in the largest depth group.

**Comment by jflowernet** [comment]
The new `data_to_planning_grid` function uses `terra::project` or`terra::resample` where appropriate with `method = "average"` which calculates an area weighted average, and for sf planning grids, `exactextractr::exact_extract(fun = 'mean')` which also calculates an area weighted average. We can therefore use the `data_to_planning_grid` function to get the data to planning grid, and then classify, which is the best option.
